### ISSUE TITLE
Intermittent orderId not loading meaning lockbond page redirect doesnt work.

### ISSUE THREAD

**Issue by isaacknjama** [civkit/civkit-frontend#36]
A number of orders do not succeed due to duplicate order id error:

```
Starting addOrderAndGenerateInvoice with data: {
  order_details: 'Civkit Africa Order #4',
  amount_msat: 1500,
  currency: 'KES',
  payment_method: 'Credit Card',
  status: 'Pending',
  type: 0,
  customer_id: 21
}
Order inserted: {
  order_id: 40,
  customer_id: 21,
  order_details: 'Civkit Africa Order #4',
  amount_msat: 1500,
  currency: 'KES',
  payment_method: 'Credit Card',
  status: 'Pending',
  created_at: 2024-10-03T07:13:24.865Z,
  escrow_status: 'pending',
  type: 0,
  premium: 0,
  taker_customer_id: null
}
Generating hold invoice
Transaction failed: Error: Invalid orderId provided
    at file:///root/civkit-api/dist/services/invoiceService.js:26:19
    at Generator.next (<anonymous>)
    at file:///root/civkit-api/dist/services/invoiceService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///root/civkit-api/dist/services/invoiceService.js:3:12)
    at postHoldinvoice (file:///root/civkit-api/dist/services/invoiceService.js:23:12)
    at file:///root/civkit-api/dist/services/orderService.js:36:43
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/civkit-api/dist/services/orderService.js:4:58)
Error in createOrder: Error: Invalid orderId provided
    at file:///root/civkit-api/dist/services/invoiceService.js:26:19
    at Generator.next (<anonymous>)
    at file:///root/civkit-api/dist/services/invoiceService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///root/civkit-api/dist/services/invoiceService.js:3:12)
    at postHoldinvoice (file:///root/civkit-api/dist/services/invoiceService.js:23:12)
    at file:///root/civkit-api/dist/services/orderService.js:36:43
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/civkit-api/dist/services/orderService.js:4:58)
```

1. Identify why this is occurring. Seems to be an async issue with the `Create Order` page. Basically, it has to save the orderId before redirect happens. Potential fix in `Take Order` button.
2. Implement a delay before the redirect and see if that fixes the bug

https://github.com/civkit/civkit-frontend/blob/main/pages/create-order.tsx

https://github.com/civkit/civkit-frontend/blob/main/components/CreateOrderForm.tsx (Line 77)

**Comment by MarketMadi** [comment]
fixed
